MovieApp.AdminUI/Controllers/CastController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using MovieApp.Application.Dtos.CastDtos;
using MovieApp.Application.Dtos.MovieDtos;

namespace CastApp.AdminUI.Controllers
{
    public class CastController : Controller
    {
        private readonly HttpClient _client;

        public CastController(HttpClient client)
        {
            _client = client;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _client.GetStringAsync("https://localhost:7265/api/Cast");
            var Cast = JsonConvert.DeserializeObject<List<GetAllCastDto>>(response);
            return View(Cast);
        }

        [HttpGet]
        public async Task<IActionResult> CreateCast()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCast(CreateCastDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            var jsonContent = new StringContent(JsonConvert.SerializeObject(dto), Encoding.UTF8, "application/json");
            var response = await _client.PostAsync("https://localhost:7265/api/Cast", jsonContent);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Oyuncu eklenirken bir hata oluştu.");
            return View(dto);
        }

        [HttpGet]
        [Route("/Cast/Update/{id}")]
        public async Task<IActionResult> UpdateCast(string id)
        {
            ViewBag.Movies = await GetMoviesAsync(id);
            var response = await _client.GetStringAsync("https://localhost:7265/api/Cast/" + id);
            var cast = JsonConvert.DeserializeObject<UpdateCastDto>(response);
            return View(cast);
        }

        [HttpPost]
        [Route("/Cast/Update/{id}")]
        public async Task<IActionResult> UpdateCast(UpdateCastDto dto, string id)
        {
            if(dto.Id != id)
            {
                ModelState.AddModelError(string.Empty, "Id uyuşmuyor");
                return View(dto);
            }

            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            var jsonContent = new StringContent(JsonConvert.SerializeObject(dto), Encoding.UTF8, "application/json");
            var response = await _client.PutAsync("https://localhost:7265/api/Cast/" + id, jsonContent);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Oyuncu güncellenirken bir hata oluştu.");
            return View(dto);
        }

        [HttpGet]
        [Route("/Cast/Delete/{id}")]
        public async Task<IActionResult> RemoveCast(Guid id)
        {
            var response = await _client.GetStringAsync("https://localhost:7265/api/Cast/" + id);
            var cast = JsonConvert.DeserializeObject<GetByIdCastDto>(response);
            return View(cast);
        }

        [HttpPost]
        [Route("/Cast/Delete/{id}")]
        public async Task<IActionResult> RemoveCast(string id)
        {
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Delete,
                RequestUri = new Uri("https://localhost:7265/api/Cast/" + id),
                Content = new StringContent(JsonConvert.SerializeObject(new { Id = id }), Encoding.UTF8, "application/json")
            };

            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Kategori güncellenirken bir hata oluştu.");
            return View();
        }

        private async Task<List<GetAllMovieDto>> GetMoviesAsync(string id)
        {
            var response = await _client.GetStringAsync("https://localhost:7265/api/Movie/category/" + id);
            return JsonConvert.DeserializeObject<List<GetAllMovieDto>>(response);
        }
    }
}

MovieApp.AdminUI/Views/Cast/CreateCast.cshtml
@model CreateCastDto

@{
    ViewData["Title"] = "CreateCast";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="chart-box">
    <h4>Comment Create</h4>
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger" role="alert">
            <strong>Hata!</strong> Lütfen aşağıdaki hataları düzeltin:
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }

    <div class="row">
        <form method="post">
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">FullName</label>
                    <input type="text" class="form-control" asp-for="FullName" placeholder="FullName">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">Image</label>
                    <input type="text" class="form-control" asp-for="ImgUrl" placeholder="Image">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">Biography</label>
                    <textarea type="text" class="form-control" asp-for="Biography" placeholder="Biography"></textarea>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">Country</label>
                    <input type="text" class="form-control" asp-for="Country" placeholder="Country">
                </div>
            </div>
            <div class="col-md-6">
                <div class="radio">
                    <label>
                        <input type="radio" name="Gender" asp-for="Gender" value="True" checked="">
                        Male
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="Gender" asp-for="Gender" value="False">
                        Female
                    </label>
                </div>
            </div>
            <div class="col-md-6">
                <label class="control-label">Date of Birth</label>
                <input type="date" class="form-control" asp-for="DateOfBirth" placeholder="Date of Birth">
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </form>
    </div>
</div>

MovieApp.AdminUI/Views/Cast/Index.cshtml
@model List<GetAllCastDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="chart-box">
    <div class="d-flex justify-content-between">
        <div class="col-4"><h4>Cast List</h4></div>
        <div class="col-4"><a href="/Cast/CreateCast" class="btn btn-success">Create</a></div>
    </div>
    <div class="bs-example" data-example-id="bordered-table">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>FullName</th>
                    <th>Image</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cast in Model)
                {
                    <tr>
                        <th>@cast.Id</th>
                        <td>@cast.FullName</td>
                        <td><img src=@cast.ImgUrl width="50px" height="50px"/></td>
                        <td>
                            <a href="/Cast/Update/@cast.Id" class="btn btn-warning">Edit</a>
                            <a href="/Cast/Delete/@cast.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MovieApp.AdminUI/Views/Cast/RemoveCast.cshtml
@model GetByIdCastDto

@{
    ViewData["Title"] = "RemoveCast";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Remove Cast</h2>
    <h4>#@Model.Id - @Model.FullName silmek istediğinizden emin misiniz?</h4>
    <div class="d-inline-flex gap-2">
        <form asp-action="RemoveCast" asp-controller="Cast" method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-danger">Evet</button>
            <a href="/Cast" class="btn btn-warning">Hayır</a>
        </form>
    </div>
</div>

MovieApp.AdminUI/Views/Cast/UpdateCast.cshtml
@model UpdateCastDto

@{
    ViewData["Title"] = "UpdateCast";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="chart-box">
    <h4>Comment Create</h4>
    <input type="text" class="form-control" value="@Model.Id" asp-for="Id" readonly />
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger" role="alert">
            <strong>Hata!</strong> Lütfen aşağıdaki hataları düzeltin:
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }

    <div class="row">
        <form method="post">
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">FullName</label>
                    <input type="text" class="form-control" asp-for="FullName" placeholder="FullName">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">Image</label>
                    <input type="text" class="form-control" asp-for="ImgUrl" placeholder="Image">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">Biography</label>
                    <textarea type="text" class="form-control" asp-for="Biography" placeholder="Biography"></textarea>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-feedback">
                    <label class="control-label">Country</label>
                    <input type="text" class="form-control" asp-for="Country" placeholder="Country">
                </div>
            </div>
            <div class="col-md-6">
                <div class="radio">
                    <label>
                        <input type="radio" name="Gender" asp-for="Gender" value="True" checked="">
                        Male
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="Gender" asp-for="Gender" value="False">
                        Female
                    </label>
                </div>
            </div>
            <div class="col-md-6">
                <label class="control-label">Date of Birth</label>
                <input type="date" class="form-control" asp-for="DateOfBirth" placeholder="Date of Birth">
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </form>
    </div>
</div>